services:
  lena-agent:
    build: .
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./docs:/app/docs
      - ./config:/app/config

  lena-agent-api:
    build: .
    env_file:
      - .env
    environment:
      - SERVER_MODE=api
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
      - ./config:/app/config
